import { FALLBACKS } from "./fallback-data";

/**
 * Snapshot fallback for aggregate endpoints.
 *
 * The D1 free tier meters rows read per day; when the quota limiter rejects a
 * query the worker would otherwise return 500. These endpoints only serve
 * pre-aggregated data (regenerated by the daily sync), so serving a baked-in
 * snapshot keeps the dashboard usable while the limiter is closed.
 *
 * Responses are marked `x-ksadb-cache: FALLBACK` and sent with
 * `cache-control: no-store` so a snapshot is never written into the runtime
 * Cache API and can never poison the edge cache.
 */
export function fallbackFor(url: string): Response | null {
  const { pathname, search } = new URL(url);
  const payload = FALLBACKS[`GET ${pathname}${search}`];
  if (payload === undefined) return null;
  return Response.json(payload, {
    headers: {
      "cache-control": "no-store",
      "x-ksadb-cache": "FALLBACK",
    },
  });
}
